version: "3.2"
services: 
          Backend:
                  container_name: ${ENV:-dev}-app-vevent
                  build: ./
                  image: ${ENV:-dev}-app-image
                #   ports:
                #       - 8080:8080
                  environment:
                      - SPRING_PROFILES_ACTIVE=${ENV:-dev}
                  restart: always
networks:
        default:
                external:
                        name: capstone-${ENV:-dev}-vevent