version: "3.2"
services: 
          Backend:
                  container_name: be_container
                  build: ./
                  image: be_image
                #   ports:
                #       - 8080:8080
                  restart: always
networks:
        default:
                external:
                        name: capstone-vevent