version: "3.2"
services: 
          Proxy:
                  container_name: nginx_prox
                  image: nginx
                  ports:
                      - "80:80"
                      - "443:443"
                  network_mode: bridge
                  networks:
                      - development
                      - production
                      - tester
                  restart: always
                  volumes:
                      - ./nginx.conf:/etc/nginx/conf.d/default.conf
                      - /home/sysadmin/certificateFiles/:/etc/nginx/ssl/
networks:
        development:
                external:
                        name: capstone-dev-vevent
        production:
                external:
                        name: capstone-prod-vevent
        tester:
                external:
                        name: capstone-qa-vevent
                        