version: "3.2"
services: 
          Proxy:
                  container_name: nginx_prox
                  image: nginx
                  ports:
                      - "80:80"
                      - "443:443"
                  restart: always
                  volumes:
                      - ./nginx.conf:/etc/nginx/conf.d/default.conf
                      - /home/sysadmin/certificateFiles/:/etc/nginx/ssl/
networks:
        capstone-dev-vevent:
                external: true
        capstone-prod-vevent:
                external: true
        capstone-qa-vevent:
                external: true
                        