version: "3.2"

services: 
          proxy:
                  container_name: nginx_prox
                  image: nginx
                  ports:
                      - "80:80"
                      - "443:443"
                  networks:
                      - capstone-dev-vevent
                      - capstone-prod-vevent
                      - capstone-qa-vevent
                  restart: always
                  volumes:
                      - ./nginx.conf:/etc/nginx/conf.d/default.conf
                      - /home/sysadmin/certificateFiles/:/etc/nginx/ssl/
networks:
        capstone-dev-vevent:
                external: true
        capstone-peod-vevent:
                external: true
        capstone-qa-vevent:
                external: true

                        