version: "3.2"

services: 
          proxy:
                  container_name: nginx_prox
                  image: nginx
                  ports:
                      - "80:80"
                      - "443:443"
                  networks:
                      - networkDev
                      - networkProd
                      - networkQA
                  restart: always
                  volumes:
                      - ./nginx.conf:/etc/nginx/conf.d/default.conf
                      - /home/sysadmin/certificateFiles/:/etc/nginx/ssl/
networks:
        networkDev:
                external:
                        name: capstone-dev-vevent
        networkProd:
                external:
                        name: capstone-prod-vevent
        networkQA:
                external:
                        name: capstone-qa-vevent


                        