// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV6las7NHLtxSHlY3MzHEavjUt8Wwhz_4',
    appId: '1:494710804612:web:e538306f1e9bae5dc472d1',
    messagingSenderId: '494710804612',
    projectId: 'vevent-capstone',
    authDomain: 'vevent-capstone.firebaseapp.com',
    storageBucket: 'vevent-capstone.appspot.com',
    measurementId: 'G-1642XRRDK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtLDEwwZXCA_9pQtyPEe7xAiI9ET0kD6s',
    appId: '1:494710804612:android:016d0944781f7214c472d1',
    messagingSenderId: '494710804612',
    projectId: 'vevent-capstone',
    storageBucket: 'vevent-capstone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqxvc6qIYKRLefRzZ4lT54nzRTWqit3xM',
    appId: '1:494710804612:ios:c7d4bda934fc3361c472d1',
    messagingSenderId: '494710804612',
    projectId: 'vevent-capstone',
    storageBucket: 'vevent-capstone.appspot.com',
    iosBundleId: 'com.example.veventFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqxvc6qIYKRLefRzZ4lT54nzRTWqit3xM',
    appId: '1:494710804612:ios:27b423492601b066c472d1',
    messagingSenderId: '494710804612',
    projectId: 'vevent-capstone',
    storageBucket: 'vevent-capstone.appspot.com',
    iosBundleId: 'com.example.veventFlutter.RunnerTests',
  );
}
