name: Build Docker Container for Development Server

on:
  push:
    branches: [ "dev" ]


jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Shutdown Container
      run: | 
        pwd
        docker compose -f docker/docker-compose.yml down
        docker compose -f reverse_proxy/docker-compose-proxy.yml down
        # docker compose -f vevent_MySQL/docker-compose.yml down
        
    - name: Build Container
      run: |
        docker compose -f docker/docker-compose.yml --env-file docker/.env.dev up -d --build
        docker compose -f reverse_proxy/docker-compose-proxy.yml up -d --build
        # docker compose -f docker-compose.yml --env-file .env.prod up -d --build
        # docker compose -f docker-compose.yml --env-file .env.prod up -d --build
