# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Docker Container

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Shutdown Container
      run: | 
        docker compose -f vevent_spring/docker-compose.yml down
        docker compose -f vevent_MySQL/docker-compose.yml down
        
    - name: Build Container
      run: |
        docker compose -f vevent_spring/docker-compose.yml up -d --build
        docker compose -f vevent_MySQL/docker-compose.yml up -d --build
