name: Build Docker Container for Tester Server

on:
  push:
    branches: [ "tester" ]


jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Shutdown Container
      run: | 
        docker system prune -a
        docker volume prune
        docker images prune
        docker compose -f docker/docker-compose-qa.yml down 
        docker compose -f reverse_proxy/docker-compose-proxy.yml down
        
    - name: Build Container
      run: |
        docker compose -f docker/docker-compose-qa.yml --env-file docker/.env.qa up -d --build
        docker compose -f reverse_proxy/docker-compose-proxy.yml up -d --build

